name: flutter_code_testx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#ffffff" # white
  image: assets/splash.png

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

